In [34]:
import pandas as pd

In [35]:
df_personas=pd.read_csv(r"C:\Users\User\Documents\Ejercicio de clase - Hoja 1.csv",header=1)
display(df_personas)

,Unnamed: 0,Unnamed: 1,Nombre,Apellido,Edad,Género,Nivel educativo
0,NaN,NaN,Andres,Mancera,17,Masculino,Bachiller
1,NaN,NaN,Carlos,Perez,25,Indefinido,Bachiller
2,NaN,NaN,Emilia,Garzon,35,Femenino,Universitario
3,NaN,NaN,Juan,Montoya,23,M,Tecnologo
4,NaN,NaN,Sara,Pardo,26,f,profesional
5,NaN,NaN,María,Lopez,45,F,secundaria
6,NaN,NaN,juan,perez,36,m,Universitario
7,NaN,NaN,ANA,GOMEZ,NaN,Femenino,universidad
8,NaN,NaN,Pedro,NaN,abc,M,primaria
9,NaN,NaN,Luisa,Torres,X,NaN,bachillerato
10,NaN,NaN,carlos,ramirez,NaN,M,uni
11,NaN,NaN,Marta,Diaz,200,F,Secundaria
12,NaN,NaN,NaN,Herrera,NaN,F,secundaria
13,NaN,NaN,Diego,Ruiz,57,Masculino,Universidad
14,NaN,NaN,Sofia,Castro,NaN,F,doctorado
15,NaN,NaN,Andres,Lopez123,3459,M,secundaria
16,NaN,NaN,Laura,Perez,0.5,F,sec
17,NaN,NaN,Felipe,Gomez,0,M,NaN
18,NaN,NaN,Camila,Rojas,g,femenino,Universitaria
19,NaN,NaN,roberto,Sanchez,b,m,bachiller
20,NaN,NaN,Oscar,Cañas,NaN,M,Universidad
21,NaN,NaN,Valentina,Martínez,19,F,Secundaria
22,NaN,NaN,sebastian,gomez,17,m,bachillerato
23,NaN,NaN,ANDRES,ROJAS,22,Masculino,Universidad
24,NaN,NaN,Paula,Lopez,NaN,F,sec
25,NaN,NaN,Jorge,Diaz,twenty,M,universitario
26,NaN,NaN,Daniela,Castro,21,femenino,Uni
27,NaN,NaN,Miguel,Suarez,18,M,secundaria
28,NaN,NaN,Lucia,fernandez,20,F,Universitaria
29,NaN,NaN,Santiago,Martinez,16,m,primaria
30,NaN,NaN,Camilo,Garcia,19,Masculino,bachiller
31,NaN,NaN,Elena,Ruiz,18,F,Sec
32,NaN,NaN,Oscar,Lopez,25,M,doctorado
33,NaN,NaN,Natalia,Pérez,20,NaN,Universidad
34,NaN,NaN,Ricardo,Sanchez,23,M,uni
35,NaN,NaN,Patricia,Gomez,21,F,secundaria
36,NaN,NaN,Alberto,Hernandez,abc,M,Secundaria
37,NaN,NaN,Monica,Diaz,19,Femenino,NaN
38,NaN,NaN,Fernando,Castro,17,m,bachiller
39,NaN,NaN,Julian,Ramirez,22,M,Universidad
40,NaN,NaN,Gabriela,Torres,20,F,universitaria

In [36]:
df_personas=df_personas.drop(columns=["Unnamed: 0", "Unnamed: 1" ])
display(df_personas)

       Nombre   Apellido    Edad      Género Nivel educativo
0      Andres    Mancera      17   Masculino       Bachiller
1      Carlos      Perez      25  Indefinido       Bachiller
2      Emilia     Garzon      35    Femenino   Universitario
3        Juan    Montoya      23           M       Tecnologo
4        Sara      Pardo      26           f     profesional
5       María      Lopez      45           F      secundaria
6        juan      perez      36           m   Universitario
7         ANA      GOMEZ     NaN    Femenino     universidad
8       Pedro        NaN     abc           M        primaria
9       Luisa     Torres       X         NaN    bachillerato
10     carlos    ramirez     NaN           M             uni
11      Marta       Diaz     200           F      Secundaria
12        NaN    Herrera     NaN           F      secundaria
13      Diego       Ruiz      57   Masculino     Universidad
14      Sofia     Castro     NaN           F       doctorado
15     Andres   Lopez123    3459           M      secundaria
16      Laura      Perez     0.5           F             sec
17     Felipe      Gomez       0           M             NaN
18     Camila      Rojas       g    femenino   Universitaria
19    roberto    Sanchez       b           m       bachiller
20      Oscar      Cañas     NaN           M     Universidad
21  Valentina   Martínez      19           F      Secundaria
22  sebastian      gomez      17           m    bachillerato
23     ANDRES      ROJAS      22   Masculino     Universidad
24      Paula      Lopez     NaN           F             sec
25      Jorge       Diaz  twenty           M   universitario
26    Daniela     Castro      21    femenino             Uni
27     Miguel     Suarez      18           M      secundaria
28      Lucia  fernandez      20           F   Universitaria
29   Santiago   Martinez      16           m        primaria
30     Camilo     Garcia      19   Masculino       bachiller
31      Elena       Ruiz      18           F             Sec
32      Oscar      Lopez      25           M       doctorado
33    Natalia      Pérez      20         NaN     Universidad
34    Ricardo    Sanchez      23           M             uni
35   Patricia      Gomez      21           F      secundaria
36    Alberto  Hernandez     abc           M      Secundaria
37     Monica       Diaz      19    Femenino             NaN
38   Fernando     Castro      17           m       bachiller
39     Julian    Ramirez      22           M     Universidad
40   Gabriela     Torres      20           F   universitaria

In [37]:
df_personas.rename(columns={"Nombre":"NOMBRE","Apellido":"APELLIDO","Edad":"EDAD","Género":"GENERO", "Nivel educativo":"NIVEL_EDUCATIVO"}, inplace=True)
display(df_personas)

       NOMBRE   APELLIDO    EDAD      GENERO NIVEL_EDUCATIVO
0      Andres    Mancera      17   Masculino       Bachiller
1      Carlos      Perez      25  Indefinido       Bachiller
2      Emilia     Garzon      35    Femenino   Universitario
3        Juan    Montoya      23           M       Tecnologo
4        Sara      Pardo      26           f     profesional
5       María      Lopez      45           F      secundaria
6        juan      perez      36           m   Universitario
7         ANA      GOMEZ     NaN    Femenino     universidad
8       Pedro        NaN     abc           M        primaria
9       Luisa     Torres       X         NaN    bachillerato
10     carlos    ramirez     NaN           M             uni
11      Marta       Diaz     200           F      Secundaria
12        NaN    Herrera     NaN           F      secundaria
13      Diego       Ruiz      57   Masculino     Universidad
14      Sofia     Castro     NaN           F       doctorado
15     Andres   Lopez123    3459           M      secundaria
16      Laura      Perez     0.5           F             sec
17     Felipe      Gomez       0           M             NaN
18     Camila      Rojas       g    femenino   Universitaria
19    roberto    Sanchez       b           m       bachiller
20      Oscar      Cañas     NaN           M     Universidad
21  Valentina   Martínez      19           F      Secundaria
22  sebastian      gomez      17           m    bachillerato
23     ANDRES      ROJAS      22   Masculino     Universidad
24      Paula      Lopez     NaN           F             sec
25      Jorge       Diaz  twenty           M   universitario
26    Daniela     Castro      21    femenino             Uni
27     Miguel     Suarez      18           M      secundaria
28      Lucia  fernandez      20           F   Universitaria
29   Santiago   Martinez      16           m        primaria
30     Camilo     Garcia      19   Masculino       bachiller
31      Elena       Ruiz      18           F             Sec
32      Oscar      Lopez      25           M       doctorado
33    Natalia      Pérez      20         NaN     Universidad
34    Ricardo    Sanchez      23           M             uni
35   Patricia      Gomez      21           F      secundaria
36    Alberto  Hernandez     abc           M      Secundaria
37     Monica       Diaz      19    Femenino             NaN
38   Fernando     Castro      17           m       bachiller
39     Julian    Ramirez      22           M     Universidad
40   Gabriela     Torres      20           F   universitaria

In [38]:
df_personas=df_personas.dropna(subset=["NOMBRE","APELLIDO"])
display(df_personas)

       NOMBRE   APELLIDO    EDAD      GENERO NIVEL_EDUCATIVO
0      Andres    Mancera      17   Masculino       Bachiller
1      Carlos      Perez      25  Indefinido       Bachiller
2      Emilia     Garzon      35    Femenino   Universitario
3        Juan    Montoya      23           M       Tecnologo
4        Sara      Pardo      26           f     profesional
5       María      Lopez      45           F      secundaria
6        juan      perez      36           m   Universitario
7         ANA      GOMEZ     NaN    Femenino     universidad
9       Luisa     Torres       X         NaN    bachillerato
10     carlos    ramirez     NaN           M             uni
11      Marta       Diaz     200           F      Secundaria
13      Diego       Ruiz      57   Masculino     Universidad
14      Sofia     Castro     NaN           F       doctorado
15     Andres   Lopez123    3459           M      secundaria
16      Laura      Perez     0.5           F             sec
17     Felipe      Gomez       0           M             NaN
18     Camila      Rojas       g    femenino   Universitaria
19    roberto    Sanchez       b           m       bachiller
20      Oscar      Cañas     NaN           M     Universidad
21  Valentina   Martínez      19           F      Secundaria
22  sebastian      gomez      17           m    bachillerato
23     ANDRES      ROJAS      22   Masculino     Universidad
24      Paula      Lopez     NaN           F             sec
25      Jorge       Diaz  twenty           M   universitario
26    Daniela     Castro      21    femenino             Uni
27     Miguel     Suarez      18           M      secundaria
28      Lucia  fernandez      20           F   Universitaria
29   Santiago   Martinez      16           m        primaria
30     Camilo     Garcia      19   Masculino       bachiller
31      Elena       Ruiz      18           F             Sec
32      Oscar      Lopez      25           M       doctorado
33    Natalia      Pérez      20         NaN     Universidad
34    Ricardo    Sanchez      23           M             uni
35   Patricia      Gomez      21           F      secundaria
36    Alberto  Hernandez     abc           M      Secundaria
37     Monica       Diaz      19    Femenino             NaN
38   Fernando     Castro      17           m       bachiller
39     Julian    Ramirez      22           M     Universidad
40   Gabriela     Torres      20           F   universitaria

In [39]:
df_personas.info()

<class 'pandas.DataFrame'>
Index: 39 entries, 0 to 40
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NOMBRE           39 non-null     str
 1   APELLIDO         39 non-null     str
 2   EDAD             34 non-null     str
 3   GENERO           37 non-null     str
 4   NIVEL_EDUCATIVO  37 non-null     str
dtypes: str(5)
memory usage: 1.8 KB

In [40]:
df_personas.loc[9,"EDAD"]= None
df_personas.loc[18,"EDAD"]= None
df_personas.loc[19,"EDAD"]= None
df_personas.loc[25,"EDAD"]= None
df_personas.loc[36,"EDAD"]= None
df_personas

       NOMBRE   APELLIDO  EDAD      GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17   Masculino       Bachiller
1      Carlos      Perez    25  Indefinido       Bachiller
2      Emilia     Garzon    35    Femenino   Universitario
3        Juan    Montoya    23           M       Tecnologo
4        Sara      Pardo    26           f     profesional
5       María      Lopez    45           F      secundaria
6        juan      perez    36           m   Universitario
7         ANA      GOMEZ   NaN    Femenino     universidad
9       Luisa     Torres   NaN         NaN    bachillerato
10     carlos    ramirez   NaN           M             uni
11      Marta       Diaz   200           F      Secundaria
13      Diego       Ruiz    57   Masculino     Universidad
14      Sofia     Castro   NaN           F       doctorado
15     Andres   Lopez123  3459           M      secundaria
16      Laura      Perez   0.5           F             sec
17     Felipe      Gomez     0           M             NaN
18     Camila      Rojas   NaN    femenino   Universitaria
19    roberto    Sanchez   NaN           m       bachiller
20      Oscar      Cañas   NaN           M     Universidad
21  Valentina   Martínez    19           F      Secundaria
22  sebastian      gomez    17           m    bachillerato
23     ANDRES      ROJAS    22   Masculino     Universidad
24      Paula      Lopez   NaN           F             sec
25      Jorge       Diaz   NaN           M   universitario
26    Daniela     Castro    21    femenino             Uni
27     Miguel     Suarez    18           M      secundaria
28      Lucia  fernandez    20           F   Universitaria
29   Santiago   Martinez    16           m        primaria
30     Camilo     Garcia    19   Masculino       bachiller
31      Elena       Ruiz    18           F             Sec
32      Oscar      Lopez    25           M       doctorado
33    Natalia      Pérez    20         NaN     Universidad
34    Ricardo    Sanchez    23           M             uni
35   Patricia      Gomez    21           F      secundaria
36    Alberto  Hernandez   NaN           M      Secundaria
37     Monica       Diaz    19    Femenino             NaN
38   Fernando     Castro    17           m       bachiller
39     Julian    Ramirez    22           M     Universidad
40   Gabriela     Torres    20           F   universitaria

In [41]:
df_personas["EDAD"]=df_personas["EDAD"].astype("Float64")
df_personas["EDAD"]=df_personas["EDAD"].astype("Int64")
df_personas.info()

<class 'pandas.DataFrame'>
Index: 39 entries, 0 to 40
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NOMBRE           39 non-null     str
 1   APELLIDO         39 non-null     str
 2   EDAD             29 non-null     Int64
 3   GENERO           37 non-null     str
 4   NIVEL_EDUCATIVO  37 non-null     str
dtypes: Int64(1), str(4)
memory usage: 2.9 KB

In [42]:
prom=((df_personas["EDAD"]).mean()).astype(int)
prom

np.int64(146)

In [43]:
df_personas["GENERO"]=df_personas["GENERO"].replace({"M":"Masculino","F":"Femenino","m":"Masculino","f":"Femenino","femenino":"Femenino","Indefinido":None})
df_personas

       NOMBRE   APELLIDO  EDAD     GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17  Masculino       Bachiller
1      Carlos      Perez    25       None       Bachiller
2      Emilia     Garzon    35   Femenino   Universitario
3        Juan    Montoya    23  Masculino       Tecnologo
4        Sara      Pardo    26   Femenino     profesional
5       María      Lopez    45   Femenino      secundaria
6        juan      perez    36  Masculino   Universitario
7         ANA      GOMEZ  <NA>   Femenino     universidad
9       Luisa     Torres  <NA>        NaN    bachillerato
10     carlos    ramirez  <NA>  Masculino             uni
11      Marta       Diaz   200   Femenino      Secundaria
13      Diego       Ruiz    57  Masculino     Universidad
14      Sofia     Castro  <NA>   Femenino       doctorado
15     Andres   Lopez123  3459  Masculino      secundaria
16      Laura      Perez     0   Femenino             sec
17     Felipe      Gomez     0  Masculino             NaN
18     Camila      Rojas  <NA>   Femenino   Universitaria
19    roberto    Sanchez  <NA>  Masculino       bachiller
20      Oscar      Cañas  <NA>  Masculino     Universidad
21  Valentina   Martínez    19   Femenino      Secundaria
22  sebastian      gomez    17  Masculino    bachillerato
23     ANDRES      ROJAS    22  Masculino     Universidad
24      Paula      Lopez  <NA>   Femenino             sec
25      Jorge       Diaz  <NA>  Masculino   universitario
26    Daniela     Castro    21   Femenino             Uni
27     Miguel     Suarez    18  Masculino      secundaria
28      Lucia  fernandez    20   Femenino   Universitaria
29   Santiago   Martinez    16  Masculino        primaria
30     Camilo     Garcia    19  Masculino       bachiller
31      Elena       Ruiz    18   Femenino             Sec
32      Oscar      Lopez    25  Masculino       doctorado
33    Natalia      Pérez    20        NaN     Universidad
34    Ricardo    Sanchez    23  Masculino             uni
35   Patricia      Gomez    21   Femenino      secundaria
36    Alberto  Hernandez  <NA>  Masculino      Secundaria
37     Monica       Diaz    19   Femenino             NaN
38   Fernando     Castro    17  Masculino       bachiller
39     Julian    Ramirez    22  Masculino     Universidad
40   Gabriela     Torres    20   Femenino   universitaria

In [44]:
df_Femeninos= df_personas[df_personas["GENERO"] == "Femenino"]
display(df_Femeninos)
cantidad_Feminino=df_Femeninos["GENERO"].count()
print("La cantidad de mujeres es:", cantidad_Feminino)

       NOMBRE   APELLIDO  EDAD    GENERO NIVEL_EDUCATIVO
2      Emilia     Garzon    35  Femenino   Universitario
4        Sara      Pardo    26  Femenino     profesional
5       María      Lopez    45  Femenino      secundaria
7         ANA      GOMEZ  <NA>  Femenino     universidad
11      Marta       Diaz   200  Femenino      Secundaria
14      Sofia     Castro  <NA>  Femenino       doctorado
16      Laura      Perez     0  Femenino             sec
18     Camila      Rojas  <NA>  Femenino   Universitaria
21  Valentina   Martínez    19  Femenino      Secundaria
24      Paula      Lopez  <NA>  Femenino             sec
26    Daniela     Castro    21  Femenino             Uni
28      Lucia  fernandez    20  Femenino   Universitaria
31      Elena       Ruiz    18  Femenino             Sec
35   Patricia      Gomez    21  Femenino      secundaria
37     Monica       Diaz    19  Femenino             NaN
40   Gabriela     Torres    20  Femenino   universitaria

La cantidad de mujeres es: 16

In [45]:
df_Masculinos= df_personas[df_personas["GENERO"] == "Masculino"]
display(df_Masculinos)
cantidad_Masculino=df_Masculinos["GENERO"].count()
print("La cantidad de mujeres es:", cantidad_Masculino)

       NOMBRE   APELLIDO  EDAD     GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17  Masculino       Bachiller
3        Juan    Montoya    23  Masculino       Tecnologo
6        juan      perez    36  Masculino   Universitario
10     carlos    ramirez  <NA>  Masculino             uni
13      Diego       Ruiz    57  Masculino     Universidad
15     Andres   Lopez123  3459  Masculino      secundaria
17     Felipe      Gomez     0  Masculino             NaN
19    roberto    Sanchez  <NA>  Masculino       bachiller
20      Oscar      Cañas  <NA>  Masculino     Universidad
22  sebastian      gomez    17  Masculino    bachillerato
23     ANDRES      ROJAS    22  Masculino     Universidad
25      Jorge       Diaz  <NA>  Masculino   universitario
27     Miguel     Suarez    18  Masculino      secundaria
29   Santiago   Martinez    16  Masculino        primaria
30     Camilo     Garcia    19  Masculino       bachiller
32      Oscar      Lopez    25  Masculino       doctorado
34    Ricardo    Sanchez    23  Masculino             uni
36    Alberto  Hernandez  <NA>  Masculino      Secundaria
38   Fernando     Castro    17  Masculino       bachiller
39     Julian    Ramirez    22  Masculino     Universidad

La cantidad de mujeres es: 20

In [46]:
data= df_personas.groupby("GENERO")["NOMBRE"].count()
print(data)

GENERO
Femenino     16
Masculino    20
Name: NOMBRE, dtype: int64

In [47]:
df_personas["NOMBRE"]=df_personas["NOMBRE"].str.capitalize()
df_personas

       NOMBRE   APELLIDO  EDAD     GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17  Masculino       Bachiller
1      Carlos      Perez    25       None       Bachiller
2      Emilia     Garzon    35   Femenino   Universitario
3        Juan    Montoya    23  Masculino       Tecnologo
4        Sara      Pardo    26   Femenino     profesional
5       María      Lopez    45   Femenino      secundaria
6        Juan      perez    36  Masculino   Universitario
7         Ana      GOMEZ  <NA>   Femenino     universidad
9       Luisa     Torres  <NA>        NaN    bachillerato
10     Carlos    ramirez  <NA>  Masculino             uni
11      Marta       Diaz   200   Femenino      Secundaria
13      Diego       Ruiz    57  Masculino     Universidad
14      Sofia     Castro  <NA>   Femenino       doctorado
15     Andres   Lopez123  3459  Masculino      secundaria
16      Laura      Perez     0   Femenino             sec
17     Felipe      Gomez     0  Masculino             NaN
18     Camila      Rojas  <NA>   Femenino   Universitaria
19    Roberto    Sanchez  <NA>  Masculino       bachiller
20      Oscar      Cañas  <NA>  Masculino     Universidad
21  Valentina   Martínez    19   Femenino      Secundaria
22  Sebastian      gomez    17  Masculino    bachillerato
23     Andres      ROJAS    22  Masculino     Universidad
24      Paula      Lopez  <NA>   Femenino             sec
25      Jorge       Diaz  <NA>  Masculino   universitario
26    Daniela     Castro    21   Femenino             Uni
27     Miguel     Suarez    18  Masculino      secundaria
28      Lucia  fernandez    20   Femenino   Universitaria
29   Santiago   Martinez    16  Masculino        primaria
30     Camilo     Garcia    19  Masculino       bachiller
31      Elena       Ruiz    18   Femenino             Sec
32      Oscar      Lopez    25  Masculino       doctorado
33    Natalia      Pérez    20        NaN     Universidad
34    Ricardo    Sanchez    23  Masculino             uni
35   Patricia      Gomez    21   Femenino      secundaria
36    Alberto  Hernandez  <NA>  Masculino      Secundaria
37     Monica       Diaz    19   Femenino             NaN
38   Fernando     Castro    17  Masculino       bachiller
39     Julian    Ramirez    22  Masculino     Universidad
40   Gabriela     Torres    20   Femenino   universitaria

In [48]:
df_personas["APELLIDO"]=df_personas["APELLIDO"].str.capitalize()
df_personas

       NOMBRE   APELLIDO  EDAD     GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17  Masculino       Bachiller
1      Carlos      Perez    25       None       Bachiller
2      Emilia     Garzon    35   Femenino   Universitario
3        Juan    Montoya    23  Masculino       Tecnologo
4        Sara      Pardo    26   Femenino     profesional
5       María      Lopez    45   Femenino      secundaria
6        Juan      Perez    36  Masculino   Universitario
7         Ana      Gomez  <NA>   Femenino     universidad
9       Luisa     Torres  <NA>        NaN    bachillerato
10     Carlos    Ramirez  <NA>  Masculino             uni
11      Marta       Diaz   200   Femenino      Secundaria
13      Diego       Ruiz    57  Masculino     Universidad
14      Sofia     Castro  <NA>   Femenino       doctorado
15     Andres   Lopez123  3459  Masculino      secundaria
16      Laura      Perez     0   Femenino             sec
17     Felipe      Gomez     0  Masculino             NaN
18     Camila      Rojas  <NA>   Femenino   Universitaria
19    Roberto    Sanchez  <NA>  Masculino       bachiller
20      Oscar      Cañas  <NA>  Masculino     Universidad
21  Valentina   Martínez    19   Femenino      Secundaria
22  Sebastian      Gomez    17  Masculino    bachillerato
23     Andres      Rojas    22  Masculino     Universidad
24      Paula      Lopez  <NA>   Femenino             sec
25      Jorge       Diaz  <NA>  Masculino   universitario
26    Daniela     Castro    21   Femenino             Uni
27     Miguel     Suarez    18  Masculino      secundaria
28      Lucia  Fernandez    20   Femenino   Universitaria
29   Santiago   Martinez    16  Masculino        primaria
30     Camilo     Garcia    19  Masculino       bachiller
31      Elena       Ruiz    18   Femenino             Sec
32      Oscar      Lopez    25  Masculino       doctorado
33    Natalia      Pérez    20        NaN     Universidad
34    Ricardo    Sanchez    23  Masculino             uni
35   Patricia      Gomez    21   Femenino      secundaria
36    Alberto  Hernandez  <NA>  Masculino      Secundaria
37     Monica       Diaz    19   Femenino             NaN
38   Fernando     Castro    17  Masculino       bachiller
39     Julian    Ramirez    22  Masculino     Universidad
40   Gabriela     Torres    20   Femenino   universitaria

In [52]:
data1= df_personas.groupby("NIVEL_EDUCATIVO")["NOMBRE"].count()
print(data1.sort_values(ascending=False))

NIVEL_EDUCATIVO
Universidad      5
secundaria       4
Secundaria       3
bachiller        3
Bachiller        2
uni              2
Universitario    2
bachillerato     2
doctorado        2
sec              2
Universitaria    2
Sec              1
Tecnologo        1
Uni              1
profesional      1
primaria         1
universidad      1
universitaria    1
universitario    1
Name: NOMBRE, dtype: int64

In [61]:
df_personas["NIVEL_EDUCATIVO"]=df_personas["NIVEL_EDUCATIVO"].str.capitalize()
data1= df_personas.groupby("NIVEL_EDUCATIVO")["NOMBRE"].count()
print(data1.sort_values(ascending=False))

NIVEL_EDUCATIVO
Bachillerato    17
Universidad     16
Doctorado        2
Primaria         1
Tecnologo        1
Name: NOMBRE, dtype: int64

In [60]:
df_personas.loc[df_personas["NIVEL_EDUCATIVO"].str.contains("Uni"), "NIVEL_EDUCATIVO"]="Universidad"
df_personas.loc[df_personas["NIVEL_EDUCATIVO"].str.contains("Bach"), "NIVEL_EDUCATIVO"]="Bachillerato"
df_personas.loc[df_personas["NIVEL_EDUCATIVO"].str.contains("Sec"), "NIVEL_EDUCATIVO"]="Bachillerato"
df_personas.loc[df_personas["NIVEL_EDUCATIVO"].str.contains("Prof"), "NIVEL_EDUCATIVO"]="Universidad"
df_personas

       NOMBRE   APELLIDO  EDAD     GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17  Masculino    Bachillerato
1      Carlos      Perez    25       None    Bachillerato
2      Emilia     Garzon    35   Femenino     Universidad
3        Juan    Montoya    23  Masculino       Tecnologo
4        Sara      Pardo    26   Femenino     Universidad
5       María      Lopez    45   Femenino    Bachillerato
6        Juan      Perez    36  Masculino     Universidad
7         Ana      Gomez  <NA>   Femenino     Universidad
9       Luisa     Torres  <NA>        NaN    Bachillerato
10     Carlos    Ramirez  <NA>  Masculino     Universidad
11      Marta       Diaz   200   Femenino    Bachillerato
13      Diego       Ruiz    57  Masculino     Universidad
14      Sofia     Castro  <NA>   Femenino       Doctorado
15     Andres   Lopez123  3459  Masculino    Bachillerato
16      Laura      Perez     0   Femenino    Bachillerato
17     Felipe      Gomez     0  Masculino             NaN
18     Camila      Rojas  <NA>   Femenino     Universidad
19    Roberto    Sanchez  <NA>  Masculino    Bachillerato
20      Oscar      Cañas  <NA>  Masculino     Universidad
21  Valentina   Martínez    19   Femenino    Bachillerato
22  Sebastian      Gomez    17  Masculino    Bachillerato
23     Andres      Rojas    22  Masculino     Universidad
24      Paula      Lopez  <NA>   Femenino    Bachillerato
25      Jorge       Diaz  <NA>  Masculino     Universidad
26    Daniela     Castro    21   Femenino     Universidad
27     Miguel     Suarez    18  Masculino    Bachillerato
28      Lucia  Fernandez    20   Femenino     Universidad
29   Santiago   Martinez    16  Masculino        Primaria
30     Camilo     Garcia    19  Masculino    Bachillerato
31      Elena       Ruiz    18   Femenino    Bachillerato
32      Oscar      Lopez    25  Masculino       Doctorado
33    Natalia      Pérez    20        NaN     Universidad
34    Ricardo    Sanchez    23  Masculino     Universidad
35   Patricia      Gomez    21   Femenino    Bachillerato
36    Alberto  Hernandez  <NA>  Masculino    Bachillerato
37     Monica       Diaz    19   Femenino             NaN
38   Fernando     Castro    17  Masculino    Bachillerato
39     Julian    Ramirez    22  Masculino     Universidad
40   Gabriela     Torres    20   Femenino     Universidad

In [62]:
df_personas.to_excel("data_clean.xlsx",index=False)