In [1]:
import pandas as pd

In [ ]:
df_personas=pd.read_csv(r"C:\Users\User\Documents\Ejercicio de clase - Hoja 1.csv",header=1)
display(df_personas)

In [ ]:
df_personas=df_personas.drop(columns=["Unnamed: 0", "Unnamed: 1" ])
display(df_personas)

In [54]:
df_personas.rename(columns={"Nombre":"NOMBRE","Apellido":"APELLIDO","Edad":"EDAD","Género":"GENERO", "Nivel educativo":"NIVEL_EDUCATIVO"}, inplace=True)
display(df_personas)

       NOMBRE   APELLIDO    EDAD      GENERO NIVEL_EDUCATIVO
0      Andres    Mancera      17   Masculino       Bachiller
1      Carlos      Perez      25  Indefinido       Bachiller
2      Emilia     Garzon      35    Femenino   Universitario
3        Juan    Montoya      23           M       Tecnologo
4        Sara      Pardo      26           f     profesional
5       María      Lopez      45           F      secundaria
6        juan      perez      36           m   Universitario
7         ANA      GOMEZ     NaN    Femenino     universidad
8       Pedro        NaN     abc           M        primaria
9       Luisa     Torres       X         NaN    bachillerato
10     carlos    ramirez     NaN           M             uni
11      Marta       Diaz     200           F      Secundaria
12        NaN    Herrera     NaN           F      secundaria
13      Diego       Ruiz      57   Masculino     Universidad
14      Sofia     Castro     NaN           F       doctorado
15     Andres   Lopez123    3459           M      secundaria
16      Laura      Perez     0.5           F             sec
17     Felipe      Gomez       0           M             NaN
18     Camila      Rojas       g    femenino   Universitaria
19    roberto    Sanchez       b           m       bachiller
20      Oscar      Cañas     NaN           M     Universidad
21  Valentina   Martínez      19           F      Secundaria
22  sebastian      gomez      17           m    bachillerato
23     ANDRES      ROJAS      22   Masculino     Universidad
24      Paula      Lopez     NaN           F             sec
25      Jorge       Diaz  twenty           M   universitario
26    Daniela     Castro      21    femenino             Uni
27     Miguel     Suarez      18           M      secundaria
28      Lucia  fernandez      20           F   Universitaria
29   Santiago   Martinez      16           m        primaria
30     Camilo     Garcia      19   Masculino       bachiller
31      Elena       Ruiz      18           F             Sec
32      Oscar      Lopez      25           M       doctorado
33    Natalia      Pérez      20         NaN     Universidad
34    Ricardo    Sanchez      23           M             uni
35   Patricia      Gomez      21           F      secundaria
36    Alberto  Hernandez     abc           M      Secundaria
37     Monica       Diaz      19    Femenino             NaN
38   Fernando     Castro      17           m       bachiller
39     Julian    Ramirez      22           M     Universidad
40   Gabriela     Torres      20           F   universitaria

In [55]:
df_personas=df_personas.dropna(subset=["NOMBRE","APELLIDO"])
display(df_personas)

       NOMBRE   APELLIDO    EDAD      GENERO NIVEL_EDUCATIVO
0      Andres    Mancera      17   Masculino       Bachiller
1      Carlos      Perez      25  Indefinido       Bachiller
2      Emilia     Garzon      35    Femenino   Universitario
3        Juan    Montoya      23           M       Tecnologo
4        Sara      Pardo      26           f     profesional
5       María      Lopez      45           F      secundaria
6        juan      perez      36           m   Universitario
7         ANA      GOMEZ     NaN    Femenino     universidad
9       Luisa     Torres       X         NaN    bachillerato
10     carlos    ramirez     NaN           M             uni
11      Marta       Diaz     200           F      Secundaria
13      Diego       Ruiz      57   Masculino     Universidad
14      Sofia     Castro     NaN           F       doctorado
15     Andres   Lopez123    3459           M      secundaria
16      Laura      Perez     0.5           F             sec
17     Felipe      Gomez       0           M             NaN
18     Camila      Rojas       g    femenino   Universitaria
19    roberto    Sanchez       b           m       bachiller
20      Oscar      Cañas     NaN           M     Universidad
21  Valentina   Martínez      19           F      Secundaria
22  sebastian      gomez      17           m    bachillerato
23     ANDRES      ROJAS      22   Masculino     Universidad
24      Paula      Lopez     NaN           F             sec
25      Jorge       Diaz  twenty           M   universitario
26    Daniela     Castro      21    femenino             Uni
27     Miguel     Suarez      18           M      secundaria
28      Lucia  fernandez      20           F   Universitaria
29   Santiago   Martinez      16           m        primaria
30     Camilo     Garcia      19   Masculino       bachiller
31      Elena       Ruiz      18           F             Sec
32      Oscar      Lopez      25           M       doctorado
33    Natalia      Pérez      20         NaN     Universidad
34    Ricardo    Sanchez      23           M             uni
35   Patricia      Gomez      21           F      secundaria
36    Alberto  Hernandez     abc           M      Secundaria
37     Monica       Diaz      19    Femenino             NaN
38   Fernando     Castro      17           m       bachiller
39     Julian    Ramirez      22           M     Universidad
40   Gabriela     Torres      20           F   universitaria

In [56]:
df_personas.info()

<class 'pandas.DataFrame'>
Index: 39 entries, 0 to 40
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NOMBRE           39 non-null     str
 1   APELLIDO         39 non-null     str
 2   EDAD             34 non-null     str
 3   GENERO           37 non-null     str
 4   NIVEL_EDUCATIVO  37 non-null     str
dtypes: str(5)
memory usage: 1.8 KB

In [57]:
df_personas.loc[9,"EDAD"]= None
df_personas.loc[18,"EDAD"]= None
df_personas.loc[19,"EDAD"]= None
df_personas.loc[25,"EDAD"]= None
df_personas.loc[36,"EDAD"]= None
df_personas

       NOMBRE   APELLIDO  EDAD      GENERO NIVEL_EDUCATIVO
0      Andres    Mancera    17   Masculino       Bachiller
1      Carlos      Perez    25  Indefinido       Bachiller
2      Emilia     Garzon    35    Femenino   Universitario
3        Juan    Montoya    23           M       Tecnologo
4        Sara      Pardo    26           f     profesional
5       María      Lopez    45           F      secundaria
6        juan      perez    36           m   Universitario
7         ANA      GOMEZ   NaN    Femenino     universidad
9       Luisa     Torres   NaN         NaN    bachillerato
10     carlos    ramirez   NaN           M             uni
11      Marta       Diaz   200           F      Secundaria
13      Diego       Ruiz    57   Masculino     Universidad
14      Sofia     Castro   NaN           F       doctorado
15     Andres   Lopez123  3459           M      secundaria
16      Laura      Perez   0.5           F             sec
17     Felipe      Gomez     0           M             NaN
18     Camila      Rojas   NaN    femenino   Universitaria
19    roberto    Sanchez   NaN           m       bachiller
20      Oscar      Cañas   NaN           M     Universidad
21  Valentina   Martínez    19           F      Secundaria
22  sebastian      gomez    17           m    bachillerato
23     ANDRES      ROJAS    22   Masculino     Universidad
24      Paula      Lopez   NaN           F             sec
25      Jorge       Diaz   NaN           M   universitario
26    Daniela     Castro    21    femenino             Uni
27     Miguel     Suarez    18           M      secundaria
28      Lucia  fernandez    20           F   Universitaria
29   Santiago   Martinez    16           m        primaria
30     Camilo     Garcia    19   Masculino       bachiller
31      Elena       Ruiz    18           F             Sec
32      Oscar      Lopez    25           M       doctorado
33    Natalia      Pérez    20         NaN     Universidad
34    Ricardo    Sanchez    23           M             uni
35   Patricia      Gomez    21           F      secundaria
36    Alberto  Hernandez   NaN           M      Secundaria
37     Monica       Diaz    19    Femenino             NaN
38   Fernando     Castro    17           m       bachiller
39     Julian    Ramirez    22           M     Universidad
40   Gabriela     Torres    20           F   universitaria

In [58]:
df_personas["EDAD"]=df_personas["EDAD"].astype("Float64")
df_personas["EDAD"]=df_personas["EDAD"].astype("Int64")
df_personas.info()

<class 'pandas.DataFrame'>
Index: 39 entries, 0 to 40
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NOMBRE           39 non-null     str
 1   APELLIDO         39 non-null     str
 2   EDAD             29 non-null     Int64
 3   GENERO           37 non-null     str
 4   NIVEL_EDUCATIVO  37 non-null     str
dtypes: Int64(1), str(4)
memory usage: 2.9 KB

In [72]:
prom=((df_personas["EDAD"]).mean()).astype(int)
prom

np.int64(146)

In [ ]:
df_personas["GENERO"].replace([M])