<h2 style="color:blue; text-align:center"> Ejercicio de clase </h2>

importar libreria

In [3]:
import pandas as pd

crear un dataframe

In [4]:
motos={
    "marca": ["ducatti","akt","yamaha","BMW"],
    "cilindraje":[600,150,1000,1200],
    "modelo":[2015,2018,2026,2022],
}

df=pd.DataFrame(motos)
display(df)

     marca  cilindraje  modelo
0  ducatti         600    2015
1      akt         150    2018
2   yamaha        1000    2026
3      BMW        1200    2022

In [5]:
print(df["marca"][2])

yamaha

modificar un dato

In [6]:
df.loc[1,"marca"]="honda"
df["modelo"]=[1999,1995,1993,1998]
display(df)

     marca  cilindraje  modelo
0  ducatti         600    1999
1    honda         150    1995
2   yamaha        1000    1993
3      BMW        1200    1998

modificar un valor

In [7]:
df.loc[1,"cilindraje"]=500
display(df)

     marca  cilindraje  modelo
0  ducatti         600    1999
1    honda         500    1995
2   yamaha        1000    1993
3      BMW        1200    1998

Modificar una columna

In [8]:
df["color"]=["negro","azul","verde","rojo"]
display(df)

     marca  cilindraje  modelo  color
0  ducatti         600    1999  negro
1    honda         500    1995   azul
2   yamaha        1000    1993  verde
3      BMW        1200    1998   rojo

In [9]:
df.loc[4]=["suzuki",800,2000,"gris"]
display(df)

     marca  cilindraje  modelo  color
0  ducatti         600    1999  negro
1    honda         500    1995   azul
2   yamaha        1000    1993  verde
3      BMW        1200    1998   rojo
4   suzuki         800    2000   gris

como poner una fila

In [10]:
df.loc[len(df)]=["kawasaki",1000,2003,"amarilla"]
display(df)

      marca  cilindraje  modelo     color
0   ducatti         600    1999     negro
1     honda         500    1995      azul
2    yamaha        1000    1993     verde
3       BMW        1200    1998      rojo
4    suzuki         800    2000      gris
5  kawasaki        1000    2003  amarilla

filtrar un registro

In [12]:
df_filtrado=df["cilindraje"]==1000
display(df_filtrado)

0    False
1    False
2     True
3    False
4    False
5     True
Name: cilindraje, dtype: bool

filtrado estructura nombre = df [condicion]

In [15]:
df_filtrado=df[df["cilindraje"]== 1000]
display(df_filtrado)

      marca  cilindraje  modelo     color
2    yamaha        1000    1993     verde
5  kawasaki        1000    2003  amarilla

In [17]:
df_filtrado=df[df["modelo"]>1998]
display(df_filtrado)

      marca  cilindraje  modelo     color
0   ducatti         600    1999     negro
4    suzuki         800    2000      gris
5  kawasaki        1000    2003  amarilla

dataframe con lista bidimensional

In [20]:
list_columnas=["Nombre","poblacion","area","moneda"]
list_data=[
    ["colombia",50,1100,"peso"],
    ["Brasil",120,8500,"real"],
    ["españa",50,500,"euro"],
]
df_data=pd.DataFrame(data=list_data, columns=list_columnas)
display(df_data)

     Nombre  poblacion  area moneda
0  colombia         50  1100   peso
1    Brasil        120  8500   real
2    españa         50   500   euro