In [34]:
import pandas as pd

In [35]:
list_indices= ["a","c","t","f"]
peliculas={
    "genero":["accion","comedia","terror","ficcion"],
    "año":[2000,2020,2005,2010],
    "titulo":["duro de matar", "donde estan las rubias", "saw", "avenger"]
}
df_pel=pd.DataFrame(peliculas)
display(df_pel)

    genero   año                  titulo
0   accion  2000           duro de matar
1  comedia  2020  donde estan las rubias
2   terror  2005                     saw
3  ficcion  2010                 avenger

In [8]:
df_columnas=df_pel[["genero","titulo"]]
display(df_columnas)

    genero                  titulo
0   accion           duro de matar
1  comedia  donde estan las rubias
2   terror                     saw
3  ficcion                 avenger

In [9]:
df_col=df_pel["año"]
display(df_col)

0    2000
1    2020
2    2005
3    2010
Name: año, dtype: int64

renombrar la columna

In [36]:
df_pel=df_pel.rename(columns={"prueba":"titulo"})

display(df_pel)

    genero   año                  titulo
0   accion  2000           duro de matar
1  comedia  2020  donde estan las rubias
2   terror  2005                     saw
3  ficcion  2010                 avenger

eliminar columna

In [37]:
#df_pel=df_pel.drop(columns=["año"])
display(df_pel)

    genero   año                  titulo
0   accion  2000           duro de matar
1  comedia  2020  donde estan las rubias
2   terror  2005                     saw
3  ficcion  2010                 avenger

ordenar ascendente

In [38]:
df_pel=df_pel.sort_values("año",ascending=True)
display(df_pel)

    genero   año                  titulo
0   accion  2000           duro de matar
2   terror  2005                     saw
3  ficcion  2010                 avenger
1  comedia  2020  donde estan las rubias

In [43]:
df_pel.loc[len(df_pel)]=["comedia",None,"UP"]
display(df_pel)

    genero   año                  titulo
0   accion  2000           duro de matar
2   terror  2005                     saw
3  ficcion  2010                 avenger
1  comedia  2020  donde estan las rubias
4  comedia  2003                    None
5  comedia   NaN                      UP

cuenta los datos nulos

In [45]:
print(df_pel.isnull().sum())

genero    0
año       1
titulo    1
dtype: int64

elimina registros nulos todos los datos nulos

In [48]:
df_pel.dropna(how="all")
print(df_pel)

    genero   año                  titulo
0   accion  2000           duro de matar
2   terror  2005                     saw
3  ficcion  2010                 avenger
1  comedia  2020  donde estan las rubias
4  comedia  2003                    None
5  comedia   NaN                      UP