In [1]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

importar pandas

In [2]:
import pandas as pd

SE TRAE LA TABLA DE EXCEL

In [3]:
df_data= pd.read_excel("DATOS.xlsx")
display(df_data)

   Unnamed: 0              Unnamed: 1 Unnamed: 2  Unnamed: 3   Unnamed: 4
0         NaN                  Nombre        Año      Genero  Presupuesto
1         NaN                avengers       2010      Accion          400
2         NaN                     saw       2000      Terror          100
3         NaN                    cars       2012     Animada           50
4         NaN  donde estan las rubias       2003     Comedia           20
5         NaN          michel Jackson       2026  Documental          100

In [4]:
df_data_2= pd.read_csv("DATOS_CSV.csv")
display(df_data_2)

   Unnamed: 0              Unnamed: 1 Unnamed: 2  Unnamed: 3   Unnamed: 4
0         NaN                  Nombre        Año      Genero  Presupuesto
1         NaN                avengers       2010      Accion          400
2         NaN                     saw       2000      Terror          100
3         NaN                    cars       2012     Animada           50
4         NaN  donde estan las rubias       2003     Comedia           20
5         NaN          michel Jackson       2026  Documental          100

In [5]:
df_data["director"]=["andre","federico","armando","popeye","juan","felipe"]
display(df_data)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,director
0,NaN,Nombre,Año,Genero,Presupuesto,andre
1,NaN,avengers,2010,Accion,400,federico
2,NaN,saw,2000,Terror,100,armando
3,NaN,cars,2012,Animada,50,popeye
4,NaN,donde estan las rubias,2003,Comedia,20,juan
5,NaN,michel Jackson,2026,Documental,100,felipe

exportar a excel

In [6]:
df_data.to_excel("nuevo_archivo.xlsx")

exportar a csv

In [7]:
df_data.to_csv("archivo_csv.csv")