In [82]:
import pandas as pd

list_columnas=["producto","precio","cantidad"]
list_data=[
    ["Manazanas",3000,10],
    ["Peras",2500,5],
    ["Bananas",2000,8],
    ["Mandarina",3000,12],
    ["Naranjas",2000,20],
    ["Fresas",2500,7],
]
df_frutas=pd.DataFrame(data=list_data,columns=list_columnas)
display(df_frutas)

    producto  precio  cantidad
0  Manazanas    3000        10
1      Peras    2500         5
2    Bananas    2000         8
3  Mandarina    3000        12
4   Naranjas    2000        20
5     Fresas    2500         7

agregar columnas, multiplicar dos columnas

In [83]:
df_frutas["valor_total"]= df_frutas["precio"]*df_frutas["cantidad"]
display(df_frutas)

    producto  precio  cantidad  valor_total
0  Manazanas    3000        10        30000
1      Peras    2500         5        12500
2    Bananas    2000         8        16000
3  Mandarina    3000        12        36000
4   Naranjas    2000        20        40000
5     Fresas    2500         7        17500

filtrado

In [84]:
df_filtrado=df_frutas[df_frutas["valor_total"]>20000]
display(df_filtrado)

    producto  precio  cantidad  valor_total
0  Manazanas    3000        10        30000
3  Mandarina    3000        12        36000
4   Naranjas    2000        20        40000

productos con mayores ventas

In [85]:
mayor_venta=df_frutas["valor_total"].max()
producto_max=df_frutas[df_frutas["valor_total"]== mayor_venta]
display(producto_max["producto"])

4    Naranjas
Name: producto, dtype: str

el producto con mayor ventas

In [86]:
pos_max = df_frutas["valor_total"].idxmax()
display(df_frutas.loc[pos_max,"producto"])

'Naranjas'

descuento del 10%

In [87]:
df_frutas["descuento"]=(df_frutas["valor_total"]-df_frutas["valor_total"]*0.1).astype(int)
display(df_frutas)

    producto  precio  cantidad  valor_total  descuento
0  Manazanas    3000        10        30000      27000
1      Peras    2500         5        12500      11250
2    Bananas    2000         8        16000      14400
3  Mandarina    3000        12        36000      32400
4   Naranjas    2000        20        40000      36000
5     Fresas    2500         7        17500      15750

ventas totales

In [88]:
venta_totales= df_frutas["valor_total"].sum()
print("ventas totales", venta_totales)

ventas totales 152000

In [90]:
prom_totales=(df_frutas["valor_total"].mean()).astype(int)
print("promedio ventas totales",prom_totales)

promedio ventas totales 25333

In [93]:
df_ordenado=df_frutas.sort_values("valor_total", ascending=False)
display(df_ordenado)

    producto  precio  cantidad  valor_total  descuento
4   Naranjas    2000        20        40000      36000
3  Mandarina    3000        12        36000      32400
0  Manazanas    3000        10        30000      27000
5     Fresas    2500         7        17500      15750
2    Bananas    2000         8        16000      14400
1      Peras    2500         5        12500      11250